# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\[07] Qt Designer\appdesign project\groceryfeature.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GroceryList(object):
    def setupUi(self, GroceryList):
        GroceryList.setObjectName("GroceryList")
        GroceryList.resize(393, 852)
        GroceryList.setMinimumSize(QtCore.QSize(393, 852))
        GroceryList.setMaximumSize(QtCore.QSize(393, 852))
        self.centralwidget = QtWidgets.QWidget(GroceryList)
        self.centralwidget.setMinimumSize(QtCore.QSize(393, 852))
        self.centralwidget.setMaximumSize(QtCore.QSize(393, 852))
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.groceryft = QtWidgets.QStackedWidget(self.centralwidget)
        self.groceryft.setGeometry(QtCore.QRect(1, -2, 393, 857))
        self.groceryft.setMinimumSize(QtCore.QSize(393, 852))
        self.groceryft.setMaximumSize(QtCore.QSize(393, 858))
        self.groceryft.setStyleSheet("background: none;")
        self.groceryft.setObjectName("groceryft")
        self.grocerymain = QtWidgets.QWidget()
        self.grocerymain.setStyleSheet("background : none;\n"
"")
        self.grocerymain.setObjectName("grocerymain")
        self.addNewList = QtWidgets.QPushButton(self.grocerymain)
        self.addNewList.setGeometry(QtCore.QRect(289, 746, 87, 96))
        self.addNewList.setStyleSheet("background-image: url(:/buttons/images/addbutton.png);\n"
"border: none;\n"
"box-shadow: none;\n"
"background-repeat: no-repeat;\n"
"background-position: center;")
        self.addNewList.setText("")
        self.addNewList.setFlat(True)
        self.addNewList.setObjectName("addNewList")
        self.grocerybg2 = QtWidgets.QLabel(self.grocerymain)
        self.grocerybg2.setGeometry(QtCore.QRect(-1, -2, 393, 852))
        self.grocerybg2.setMinimumSize(QtCore.QSize(393, 852))
        self.grocerybg2.setMaximumSize(QtCore.QSize(393, 852))
        self.grocerybg2.setStyleSheet("border-image: url(:/background/images/grocerybackground.png);")
        self.grocerybg2.setText("")
        self.grocerybg2.setObjectName("grocerybg2")
        self.scrollArea = QtWidgets.QScrollArea(self.grocerymain)
        self.scrollArea.setGeometry(QtCore.QRect(8, 108, 377, 680))
        self.scrollArea.setStyleSheet("background-color:transparent;")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 377, 680))
        self.scrollAreaWidgetContents.setAutoFillBackground(False)
        self.scrollAreaWidgetContents.setStyleSheet("background : none;\n"
"background-color: rgb(255, 255, 255);\n"
"border: none;")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.grocery_widget_list = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.grocery_widget_list.setGeometry(QtCore.QRect(0, 0, 373, 673))
        self.grocery_widget_list.setStyleSheet("background: none;\n"
"")
        self.grocery_widget_list.setObjectName("grocery_widget_list")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.deleteButton = QtWidgets.QPushButton(self.grocerymain)
        self.deleteButton.setGeometry(QtCore.QRect(315, 49, 42, 40))
        self.deleteButton.setText("")
        self.deleteButton.setFlat(True)
        self.deleteButton.setObjectName("deleteButton")
        self.grocerybg2.raise_()
        self.scrollArea.raise_()
        self.addNewList.raise_()
        self.deleteButton.raise_()
        self.groceryft.addWidget(self.grocerymain)
        self.grocerylist = QtWidgets.QWidget()
        self.grocerylist.setStyleSheet("")
        self.grocerylist.setObjectName("grocerylist")
        self.addNewItem = QtWidgets.QPushButton(self.grocerylist)
        self.addNewItem.setGeometry(QtCore.QRect(228, 755, 160, 89))
        self.addNewItem.setStyleSheet("border: none;\n"
"box-shadow: none;\n"
"background-image: url(:/buttons/images/ADD.png);\n"
"background-repeat: no-repeat;\n"
"background-position: center;")
        self.addNewItem.setText("")
        self.addNewItem.setFlat(True)
        self.addNewItem.setObjectName("addNewItem")
        self.grocerybg = QtWidgets.QLabel(self.grocerylist)
        self.grocerybg.setGeometry(QtCore.QRect(-1, -2, 393, 852))
        self.grocerybg.setMinimumSize(QtCore.QSize(393, 852))
        self.grocerybg.setMaximumSize(QtCore.QSize(393, 852))
        self.grocerybg.setStyleSheet("border-image: url(:/background/images/Grocery.png);")
        self.grocerybg.setText("")
        self.grocerybg.setObjectName("grocerybg")
        self.grocerybackbutton = QtWidgets.QPushButton(self.grocerylist)
        self.grocerybackbutton.setGeometry(QtCore.QRect(14, 51, 39, 40))
        self.grocerybackbutton.setStyleSheet("border: none;\n"
"box-shadow: none;\n"
"")
        self.grocerybackbutton.setText("")
        self.grocerybackbutton.setObjectName("grocerybackbutton")
        self.grocery_list_name = QtWidgets.QPlainTextEdit(self.grocerylist)
        self.grocery_list_name.setGeometry(QtCore.QRect(61, 46, 298, 48))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.grocery_list_name.setFont(font)
        self.grocery_list_name.setStyleSheet("background: none;\n"
"background-color: transparent;\n"
"color: rgb(255, 255, 255);")
        self.grocery_list_name.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.grocery_list_name.setObjectName("grocery_list_name")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.grocerylist)
        self.scrollArea_2.setGeometry(QtCore.QRect(-2, 173, 393, 676))
        self.scrollArea_2.setMinimumSize(QtCore.QSize(393, 0))
        self.scrollArea_2.setMaximumSize(QtCore.QSize(395, 16777215))
        self.scrollArea_2.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);")
        self.scrollArea_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents2.setGeometry(QtCore.QRect(0, 0, 393, 676))
        self.scrollAreaWidgetContents2.setMinimumSize(QtCore.QSize(393, 0))
        self.scrollAreaWidgetContents2.setMaximumSize(QtCore.QSize(393, 16777215))
        self.scrollAreaWidgetContents2.setStyleSheet("background : none;\n"
"background-color: rgb(255, 255, 255);\n"
"border: none;")
        self.scrollAreaWidgetContents2.setObjectName("scrollAreaWidgetContents2")
        self.item_widget = QtWidgets.QWidget(self.scrollAreaWidgetContents2)
        self.item_widget.setGeometry(QtCore.QRect(1, 6, 393, 671))
        self.item_widget.setMinimumSize(QtCore.QSize(0, 0))
        self.item_widget.setMaximumSize(QtCore.QSize(393, 16777215))
        self.item_widget.setStyleSheet("background: none;")
        self.item_widget.setObjectName("item_widget")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents2)
        self.total_price = QtWidgets.QLabel(self.grocerylist)
        self.total_price.setGeometry(QtCore.QRect(196, 109, 162, 47))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(18)
        self.total_price.setFont(font)
        self.total_price.setAlignment(QtCore.Qt.AlignCenter)
        self.total_price.setObjectName("total_price")
        self.DeleteButton = QtWidgets.QPushButton(self.grocerylist)
        self.DeleteButton.setGeometry(QtCore.QRect(11, 785, 42, 31))
        self.DeleteButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/buttons/images/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.DeleteButton.setIcon(icon)
        self.DeleteButton.setIconSize(QtCore.QSize(30, 30))
        self.DeleteButton.setAutoDefault(False)
        self.DeleteButton.setFlat(True)
        self.DeleteButton.setObjectName("DeleteButton")
        self.grocerybg.raise_()
        self.scrollArea_2.raise_()
        self.addNewItem.raise_()
        self.grocery_list_name.raise_()
        self.grocerybackbutton.raise_()
        self.total_price.raise_()
        self.DeleteButton.raise_()
        self.groceryft.addWidget(self.grocerylist)
        GroceryList.setCentralWidget(self.centralwidget)

        self.retranslateUi(GroceryList)
        self.groceryft.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(GroceryList)

    def retranslateUi(self, GroceryList):
        _translate = QtCore.QCoreApplication.translate
        GroceryList.setWindowTitle(_translate("GroceryList", "MainWindow"))
        self.grocery_list_name.setPlainText(_translate("GroceryList", "Grocery List 1"))
        self.total_price.setText(_translate("GroceryList", "0.00"))
import images_rc
